"""add exchange_rate column to supported_currencies

Revision ID: 85b7a21ba7bd
Revises: 0001
Create Date: 2026-03-11 11:13:36.150964

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '85b7a21ba7bd'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
