"""Add supported_currencies table

Revision ID: 561b065590de
Revises: 81df4f07cb04
Create Date: 2025-09-28 08:00:51.244994

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '561b065590de'
down_revision: str | Sequence[str] | None = '81df4f07cb04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supported_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('provider_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('supported_currencies')
    # ### end Alembic commands ###
