"""added extra column to SupportedCurrency table

Revision ID: 83a7b5489af6
Revises: bf71a6bfcbaa
Create Date: 2025-09-30 22:45:14.965573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a7b5489af6'
down_revision: Union[str, Sequence[str], None] = 'bf71a6bfcbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supported_currencies', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('idx_api_call_logs_provider_called'), 'api_call_logs', ['provider_id', sa.literal_column('called_at DESC')], unique=False)
    op.create_index(op.f('idx_circuit_breaker_provider_changed'), 'circuit_breaker_logs', ['provider_id', sa.literal_column('state_changed_at DESC')], unique=False)
    op.create_index(op.f('idx_exchange_rates_currency_fetched'), 'exchange_rates', ['currency_pair_id', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_index(op.f('idx_exchange_rates_success_provider_time'), 'exchange_rates', ['is_successful', 'provider_id', sa.literal_column('fetched_at DESC')], unique=False, postgresql_where='(is_successful = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supported_currencies', 'last_updated')
    op.drop_index(op.f('idx_exchange_rates_success_provider_time'), table_name='exchange_rates')
    op.drop_index(op.f('idx_exchange_rates_currency_fetched'), table_name='exchange_rates')
    op.drop_index(op.f('idx_circuit_breaker_provider_changed'), table_name='circuit_breaker_logs')
    op.drop_index(op.f('idx_api_call_logs_provider_called'), table_name='api_call_logs')
    # ### end Alembic commands ###
