from decimal import Decimal
from typing import Protocol


class ExchangeRateProvider(Protocol):
	@property
	def name(self) -> str: ...

	async def fetch_rate(self, from_currency: str, to_currency: str) -> Decimal: ...

	async def fetch_supported_currencies(self) -> list[dict[str, str]]: ...

	async def close(self) -> None: ...
